CREATE DATABASE IF NOT EXISTS rancorrank;

USE rancorrank;

CREATE TABLE Utente (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Score INT NOT NULL DEFAULT 0,
    N_times_first INT DEFAULT 0
);
